### ISSUE TITLE
Remove "date" line from ZWR header

### ISSUE THREAD

**Issue by josephsnyder** [WorldVistA/VistA#244]
As part of ZGO

**Comment by whitten** [comment]
Why would you remove the Date Line? the ".GO" format has two lines at the beginning,  One a Header/Label and one an empty string (originally a line of M code to load the rest of the file.)
I don't know if any modern M system uses the second line as it was originally.

**Comment by shabiel** [comment]
The date line gets updated everytime we do an export, even though
there is no change to the data in the global. Thus it produces a diff
when none should be there.
